### ISSUE TITLE
Building in arm fails

### ISSUE THREAD

**Issue by d3gan** [curvehashcoin/cpuminer-curvehash#2] opened 2021-04-07 09:22 UTC
make  all-recursive
make[1]: Entering directory '/root/cpuminer-curvehash'
Making all in secp256k1
make[2]: Entering directory '/root/cpuminer-curvehash/secp256k1'
  CC       src/tests-tests.o
  CCLD     tests
  CC       src/exhaustive_tests-tests_exhaustive.o
  CCLD     exhaustive_tests
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
make[2]: Leaving directory '/root/cpuminer-curvehash/secp256k1'
Making all in compat
make[2]: Entering directory '/root/cpuminer-curvehash/compat'
make[3]: Entering directory '/root/cpuminer-curvehash/compat'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/root/cpuminer-curvehash/compat'
make[2]: Leaving directory '/root/cpuminer-curvehash/compat'
make[2]: Entering directory '/root/cpuminer-curvehash'
gcc -DHAVE_CONFIG_H -I.  -Iyes/include -Iyes/include -fno-strict-aliasing  -I./secp256k1/include -I. -Iyes/include -Iyes/include -Wno-pointer-sign -Wno-pointer-to-int-cast -DNOASM  -D__arm__ -Ofast -march=native  -Iyes/include -Iyes/include -MT cpuminer-cpu-miner.o -MD -MP -MF .deps/cpuminer-cpu-miner.Tpo -c -o cpuminer-cpu-miner.o `test -f 'cpu-miner.c' || echo './'`cpu-miner.c
In file included from cpu-miner.c:40:
/usr/include/aarch64-linux-gnu/sys/sysctl.h:21:2: warning: #warning "The <sys/sysctl.h> header is deprecated and will be removed." [-Wcpp]
   21 | #warning "The <sys/sysctl.h> header is deprecated and will be removed."
      |  ^~~~~~~
mv -f .deps/cpuminer-cpu-miner.Tpo .deps/cpuminer-cpu-miner.Po
gcc -DHAVE_CONFIG_H -I.  -Iyes/include -Iyes/include -fno-strict-aliasing  -I./secp256k1/include -I. -Iyes/include -Iyes/include -Wno-pointer-sign -Wno-pointer-to-int-cast -DNOASM  -D__arm__ -Ofast -march=native  -Iyes/include -Iyes/include -MT cpuminer-util.o -MD -MP -MF .deps/cpuminer-util.Tpo -c -o cpuminer-util.o `test -f 'util.c' || echo './'`util.c
mv -f .deps/cpuminer-util.Tpo .deps/cpuminer-util.Po
gcc -DHAVE_CONFIG_H -I.  -Iyes/include -Iyes/include -fno-strict-aliasing  -I./secp256k1/include -I. -Iyes/include -Iyes/include -Wno-pointer-sign -Wno-pointer-to-int-cast -DNOASM  -D__arm__ -Ofast -march=native  -Iyes/include -Iyes/include -MT cpuminer-api.o -MD -MP -MF .deps/cpuminer-api.Tpo -c -o cpuminer-api.o `test -f 'api.c' || echo './'`api.c
api.c:318:10: fatal error: compat/curl-for-windows/openssl/openssl/crypto/sha/sha.h: No such file or directory
  318 | #include "compat/curl-for-windows/openssl/openssl/crypto/sha/sha.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:1457: cpuminer-api.o] Error 1
make[2]: Leaving directory '/root/cpuminer-curvehash'
make[1]: *** [Makefile:3023: all-recursive] Error 1
make[1]: Leaving directory '/root/cpuminer-curvehash'
make: *** [Makefile:745: all] Error 2

**Comment by emerzon** [comment] 2021-04-13 07:26
Seema a duplicate of #1. Probably fixed by #3

**Closed as completed** 2021-04-15 16:33 UTC
